<?php


namespace app\controllers;


use app\lib\ibuypro\Rack;
use app\models\FindPath;
use yii\helpers\Json;
use yii\rest\Controller;

class FindPathController extends Controller
{

    public function init()
    {
        parent::init();
        \Yii::$app->user->enableSession = false;
        \Yii::$app->user->enableAutoLogin = false;
    }

    public function actionIndex(string $id)
    {
        $data = [
            '1' => [
                'Racks' => [
                    new Rack(["x" => 42, "y" => 44],
                        198,
                        18,
                        "Макароны",
                        "blue",
                        0)],
                new Rack(["x" => 42, "y" => 78],
                    198,
                    18,
                    "шоколад",
                    "blue",
                    0),
                new Rack(["x" => 42, "y" => 114],
                    198,
                    18,
                    "Консервы",
                    "blue",
                    0),
                new Rack(["x" => 42, "y" => 150],
                    198,
                    18,
                    "Крупа",
                    "blue",
                    0),
                new Rack(["x" => 42, "y" => 186],
                    198,
                    18,
                    "Яйцо",
                    "blue",
                    0),
                new Rack(["x" => 42, "y" => 222],
                    198,
                    18,
                    "Вода",
                    "blue",
                    0),
                new Rack(["x" => 42, "y" => 258],
                    198,
                    18,
                    "Бельё",
                    "blue",
                    0),
                new Rack(["x" => 42, "y" => 294],
                    198,
                    18,
                    "Мыло",
                    "blue",
                    0),
                new Rack(["x" => 42, "y" => 330],
                    198,
                    18,
                    "Кетчуп",
                    "blue",
                    0),
                new Rack(["x" => 264, "y" => 42],
                    198,
                    18,
                    "Сад",
                    "blue",
                    0),
                new Rack(["x" => 264, "y" => 78],
                    198,
                    18,
                    "Фасад",
                    "blue",
                    0),
                new Rack(["x" => 264, "y" => 114],
                    198,
                    18,
                    "Вата",
                    "blue",
                    0),
                new Rack(["x" => 264, "y" => 150],
                    198,
                    18,
                    "Шашлык",
                    "blue",
                    0),
                new Rack(["x" => 264, "y" => 186],
                    198,
                    18,
                    "Балык",
                    "blue",
                    0),
                new Rack(["x" => 264, "y" => 222],
                    198,
                    18,
                    "Затык",
                    "blue",
                    0),
                new Rack(["x" => 264, "y" => 258],
                    198,
                    18,
                    "Втык",
                    "blue",
                    0),
                new Rack(["x" => 264, "y" => 294],
                    198,
                    18,
                    "Утык",
                    "blue",
                    0),
                new Rack(["x" => 264, "y" => 330],
                    198,
                    18,
                    "Перетык",
                    "blue",
                    0),
                new Rack(["x" => 234, "y" => 360],
                    30,
                    30,
                    "Старт",
                    "#E74C3C",
                    0)
            ],
            '2' => [
                'Racks' => [
                    [
                        'position' => ["x" => 48, "y" => 16],
                        'width' => 198,
                        'height' => 18,
                        'label' => 'Кофе',
                        'fill' => 'blue',
                        'angle' => 0,
                        'top' => 3629,
                    ],
                    [
                        'position' => ["x" => 48, "y" => 19],
                        'width' => 198,
                        'height' => 18,
                        'label' => 'Кетчуп',
                        'fill' => 'blue',
                        'angle' => 0,
                        'top' => 5232,
                    ],
                    [
                        'position' => ["x" => 48, "y" => 23],
                        'width' => 198,
                        'height' => 18,
                        'label' => 'Консервы',
                        'fill' => 'blue',
                        'angle' => 0,
                        'top' => 9284,
                    ],
                    [
                        'position' => ["x" => 48, "y" => 12],
                        'width' => 198,
                        'height' => 18,
                        'label' => 'Чай',
                        'fill' => 'blue',
                        'angle' => 0,
                        'top' => 5875,
                    ],
                    [
                        'position' => ["x" => 48, "y" => 9],
                        'width' => 198,
                        'height' => 18,
                        'label' => 'Вино',
                        'fill' => 'blue',
                        'angle' => 0,
                        'top' => 4211,
                    ],
                    [
                        'position' => ["x" => 222, "y" => 18],
                        'width' => 198,
                        'height' => 18,
                        'label' => 'Вода',
                        'fill' => 'blue',
                        'angle' => 270,
                        'top' => 9631,
                    ],
                    [
                        'position' => ["x" => 48, "y" => 27],
                        'width' => 198,
                        'height' => 18,
                        'label' => 'Макароны',
                        'fill' => 'blue',
                        'angle' => 0,
                        'top' => 6483,
                    ],
                    [
                        'position' => ["x" => 264, "y" => 18],
                        'width' => 198,
                        'height' => 18,
                        'label' => 'Косметика',
                        'fill' => 'blue',
                        'angle' => 270,
                        'top' => 325,
                    ],
                    [
                        'position' => ["x" => 306, "y" => 18],
                        'width' => 198,
                        'height' => 18,
                        'label' => 'Хозтовары',
                        'fill' => 'blue',
                        'angle' => 270,
                        'top' => 462,
                    ],
                    [
                        'position' => ["x" => 348, "y" => 18],
                        'width' => 198,
                        'height' => 18,
                        'label' => 'Одежда',
                        'fill' => 'blue',
                        'angle' => 270,
                        'top' => 5583,
                    ],
                    [
                        'position' => ["x" => 390, "y" => 18],
                        'width' => 198,
                        'height' => 18,
                        'label' => 'Сад',
                        'fill' => 'blue',
                        'angle' => 270,
                        'top' => 6382,
                    ],
                    [
                        'position' => ["x" => 432, "y" => 18],
                        'width' => 198,
                        'height' => 18,
                        'label' => 'Видео',
                        'fill' => 'blue',
                        'angle' => 270,
                        'top' => 5103,
                    ],
                    [
                        'position' => ["x" => 270, "y" => 36],
                        'width' => 30,
                        'height' => 30,
                        'label' => 'Старт',
                        'fill' => '#E74C3C',
                        'angle' => 0,
                        'top' => 2698,
                    ],
                    [
                        'position' => ["x" => 270, "y" => 25],
                        'width' => 15,
                        'height' => 15,
                        'label' => '',
                        'fill' => 'black',
                        'angle' => 0,
                        'top' => 9331,
                    ],
                    [
                        'position' => ["x" => 270, "y" => 21],
                        'width' => 15,
                        'height' => 15,
                        'label' => '',
                        'fill' => 'black',
                        'angle' => 0,
                        'top' => 6484,
                    ],
                    [
                        'position' => ["x" => 262, "y" => 16],
                        'width' => 15,
                        'height' => 15,
                        'label' => '',
                        'fill' => 'black',
                        'angle' => 0,
                        'top' => 12,
                    ],
                    [
                        'position' => ["x" => 270, "y" => 14],
                        'width' => 15,
                        'height' => 15,
                        'label' => '',
                        'fill' => 'black',
                        'angle' => 0,
                        'top' => 2095,
                    ],
                    [
                        'position' => ["x" => 270, "y" => 10],
                        'width' => 15,
                        'height' => 15,
                        'label' => '',
                        'fill' => 'black',
                        'angle' => 0,
                        'top' => 8135,
                    ],
                    [
                        'position' => ["x" => 270, "y" => 6],
                        'width' => 15,
                        'height' => 15,
                        'label' => '',
                        'fill' => 'black',
                        'angle' => 0,
                        'top' => 9842,
                    ],
                    [
                        'position' => ["x" => 330, "y" => 6],
                        'width' => 15,
                        'height' => 15,
                        'label' => '',
                        'fill' => 'black',
                        'angle' => 0,
                        'top' => 9277,
                    ],
                    [
                        'position' => ["x" => 378, "y" => 6],
                        'width' => 15,
                        'height' => 15,
                        'label' => '',
                        'fill' => 'black',
                        'angle' => 0,
                        'top' => 7092,
                    ],
                    [
                        'position' => ["x" => 420, "y" => 6],
                        'width' => 15,
                        'height' => 15,
                        'label' => '',
                        'fill' => 'black',
                        'angle' => 0,
                        'top' => 9390,
                    ],
                    [
                        'position' => ["x" => 462, "y" => 6],
                        'width' => 15,
                        'height' => 15,
                        'label' => '',
                        'fill' => 'black',
                        'angle' => 0,
                        'top' => 9417,
                    ],
                    [
                        'position' => ["x" => 504, "y" => 6],
                        'width' => 15,
                        'height' => 15,
                        'label' => '',
                        'fill' => 'black',
                        'angle' => 0,
                        'top' => 1704,
                    ],
                    [
                        'position' => ["x" => 552, "y" => 6],
                        'width' => 15,
                        'height' => 15,
                        'label' => '',
                        'fill' => 'black',
                        'angle' => 0,
                        'top' => 7327,
                    ],
                    [
                        'position' => ["x" => 270, "y" => 30],
                        'width' => 15,
                        'height' => 15,
                        'label' => '',
                        'fill' => 'black',
                        'angle' => 0,
                        'top' => 9834,
                    ],
                    [
                        'position' => ["x" => 330, "y" => 30],
                        'width' => 15,
                        'height' => 15,
                        'label' => '',
                        'fill' => 'black',
                        'angle' => 0,
                        'top' => 7394,
                    ],
                    [
                        'position' => ["x" => 378, "y" => 30],
                        'width' => 15,
                        'height' => 15,
                        'label' => '',
                        'fill' => 'black',
                        'angle' => 0,
                        'top' => 1829,
                    ],
                    [
                        'position' => ["x" => 420, "y" => 30],
                        'width' => 15,
                        'height' => 15,
                        'label' => '',
                        'fill' => 'black',
                        'angle' => 0,
                        'top' => 2456,
                    ],
                    [
                        'position' => ["x" => 458, "y" => 30],
                        'width' => 15,
                        'height' => 15,
                        'label' => '',
                        'fill' => 'black',
                        'angle' => 0,
                        'top' => 4010,
                    ],
                    [
                        'position' => ["x" => 504, "y" => 30],
                        'width' => 15,
                        'height' => 15,
                        'label' => '',
                        'fill' => 'black',
                        'angle' => 0,
                        'top' => 3362,
                    ],
                    [
                        'position' => ["x" => 552, "y" => 30],
                        'width' => 15,
                        'height' => 15,
                        'label' => '',
                        'fill' => 'black',
                        'angle' => 0,
                        'top' => 8053,
                    ],
                    [
                        'position' => ["x" => 18, "y" => 30],
                        'width' => 15,
                        'height' => 15,
                        'label' => '',
                        'fill' => 'black',
                        'angle' => 0,
                        'top' => 9999,
                    ],
                    [
                        'position' => ["x" => 16, "y" => 25],
                        'width' => 15,
                        'height' => 15,
                        'label' => '',
                        'fill' => 'black',
                        'angle' => 0,
                        'top' => 6496,
                    ],
                    [
                        'position' => ["x" => 12, "y" => 22],
                        'width' => 15,
                        'height' => 15,
                        'label' => '',
                        'fill' => 'black',
                        'angle' => 0,
                        'top' => 9475,
                    ],
                    [
                        'position' => ["x" => 12, "y" => 18],
                        'width' => 15,
                        'height' => 15,
                        'label' => '',
                        'fill' => 'black',
                        'angle' => 0,
                        'top' => 154,
                    ],
                    [
                        'position' => ["x" => 12, "y" => 14],
                        'width' => 15,
                        'height' => 15,
                        'label' => '',
                        'fill' => 'black',
                        'angle' => 0,
                        'top' => 6982,
                    ],
                    [
                        'position' => ["x" => 12, "y" => 11],
                        'width' => 15,
                        'height' => 15,
                        'label' => '',
                        'fill' => 'black',
                        'angle' => 0,
                        'top' => 3959,
                    ],
                    [
                        'position' => ["x" => 12, "y" => 6],
                        'width' => 15,
                        'height' => 15,
                        'label' => '',
                        'fill' => 'black',
                        'angle' => 0,
                        'top' => 2515,
                    ],
                    [
                        'position' => ["x" => 132, "y" => 25],
                        'width' => 15,
                        'height' => 15,
                        'label' => '',
                        'fill' => 'green',
                        'angle' => 0,
                        'top' => 2562,
                    ],
                    [
                        'position' => ["x" => 132, "y" => 21],
                        'width' => 15,
                        'height' => 15,
                        'label' => '',
                        'fill' => 'green',
                        'angle' => 0,
                        'top' => 6825,
                    ],
                    [
                        'position' => ["x" => 132, "y" => 18],
                        'width' => 15,
                        'height' => 15,
                        'label' => '',
                        'fill' => 'green',
                        'angle' => 0,
                        'top' => 9255,
                    ],
                    [
                        'position' => ["x" => 132, "y" => 14],
                        'width' => 15,
                        'height' => 15,
                        'label' => '',
                        'fill' => 'green',
                        'angle' => 0,
                        'top' => 6807,
                    ],
                    [
                        'position' => ["x" => 132, "y" => 10],
                        'width' => 15,
                        'height' => 15,
                        'label' => '',
                        'fill' => 'green',
                        'angle' => 0,
                        'top' => 8759,
                    ],
                    [
                        'position' => ["x" => 132, "y" => 6],
                        'width' => 15,
                        'height' => 15,
                        'label' => '',
                        'fill' => 'green',
                        'angle' => 0,
                        'top' => 1416,
                    ],
                    [
                        'position' => ["x" => 334, "y" => 15],
                        'width' => 15,
                        'height' => 15,
                        'label' => '',
                        'fill' => 'green',
                        'angle' => 0,
                        'top' => 3503,
                    ],
                    [
                        'position' => ["x" => 378, "y" => 15],
                        'width' => 15,
                        'height' => 15,
                        'label' => '',
                        'fill' => 'green',
                        'angle' => 0,
                        'top' => 955,
                    ],
                    [
                        'position' => ["x" => 420, "y" => 15],
                        'width' => 15,
                        'height' => 15,
                        'label' => '',
                        'fill' => 'green',
                        'angle' => 0,
                        'top' => 4880,
                    ],
                    [
                        'position' => ["x" => 462, "y" => 16],
                        'width' => 15,
                        'height' => 15,
                        'label' => '',
                        'fill' => 'green',
                        'angle' => 0,
                        'top' => 2979,
                    ],
                    [
                        'position' => ["x" => 504, "y" => 16],
                        'width' => 15,
                        'height' => 15,
                        'label' => '',
                        'fill' => 'green',
                        'angle' => 0,
                        'top' => 743,
                    ],
                    [
                        'position' => ["x" => 294, "y" => 20],
                        'width' => 15,
                        'height' => 15,
                        'label' => '',
                        'fill' => 'green',
                        'angle' => 0,
                        'top' => 4552,
                    ],
                ],
                'Links' => [
                    [
                        "from" => 2698,
                        "to" => 9834,
                    ],
                    [
                        "from" => 9834,
                        "to" => 9331,
                    ],
                    [
                        "from" => 9331,
                        "to" => 6484,
                    ],
                    [
                        "from" => 7394,
                        "to" => 3503,
                    ],
                    [
                        "from" => 3503,
                        "to" => 9277,
                    ],
                    [
                        "from" => 6484,
                        "to" => 12,
                    ],
                    [
                        "from" => 12,
                        "to" => 2095,
                    ],
                    [
                        "from" => 2095,
                        "to" => 8135,
                    ],
                    [
                        "from" => 8135,
                        "to" => 9842,
                    ],
                    [
                        "from" => 9842,
                        "to" => 9277,
                    ],
                    [
                        "from" => 9842,
                        "to" => 1416,
                    ],
                    [
                        "from" => 9277,
                        "to" => 7092,
                    ],
                    [
                        "from" => 7092,
                        "to" => 9390,
                    ],
                    [
                        "from" => 9390,
                        "to" => 9417,
                    ],
                    [
                        "from" => 9417,
                        "to" => 1704,
                    ],
                    [
                        "from" => 1704,
                        "to" => 7327,
                    ],
                    [
                        "from" => 7327,
                        "to" => 8053,
                    ],
                    [
                        "from" => 8053,
                        "to" => 3362,
                    ],
                    [
                        "from" => 3362,
                        "to" => 4010,
                    ],
                    [
                        "from" => 4010,
                        "to" => 2456,
                    ],
                    [
                        "from" => 2456,
                        "to" => 1829,
                    ],
                    [
                        "from" => 1829,
                        "to" => 7394,
                    ],
                    [
                        "from" => 7394,
                        "to" => 9834,
                    ],
                    [
                        "from" => 9834,
                        "to" => 9999,
                    ],
                    [
                        "from" => 9999,
                        "to" => 6496,
                    ],
                    [
                        "from" => 6496,
                        "to" => 9475,
                    ],
                    [
                        "from" => 9475,
                        "to" => 154,
                    ],
                    [
                        "from" => 154,
                        "to" => 6982,
                    ],
                    [
                        "from" => 6982,
                        "to" => 3959,
                    ],
                    [
                        "from" => 3959,
                        "to" => 2515,
                    ],
                    [
                        "from" => 1416,
                        "to" => 2515,
                    ],
                    [
                        "from" => 3959,
                        "to" => 8759,
                    ],
                    [
                        "from" => 8759,
                        "to" => 8135,
                    ],
                    [
                        "from" => 6982,
                        "to" => 6807,
                    ],
                    [
                        "from" => 6807,
                        "to" => 2095,
                    ],
                    [
                        "from" => 154,
                        "to" => 9255,
                    ],
                    [
                        "from" => 9255,
                        "to" => 12,
                    ],
                    [
                        "from" => 9475,
                        "to" => 6825,
                    ],
                    [
                        "from" => 6825,
                        "to" => 6484,
                    ],
                    [
                        "from" => 6496,
                        "to" => 2562,
                    ],
                    [
                        "from" => 2562,
                        "to" => 9331,
                    ],
                    [
                        "from" => 1829,
                        "to" => 955,
                    ],
                    [
                        "from" => 955,
                        "to" => 7092,
                    ],
                    [
                        "from" => 2456,
                        "to" => 4880,
                    ],
                    [
                        "from" => 4880,
                        "to" => 9390,
                    ],
                    [
                        "from" => 4010,
                        "to" => 2979,
                    ],
                    [
                        "from" => 2979,
                        "to" => 9417,
                    ],
                    [
                        "from" => 3362,
                        "to" => 743,
                    ],
                    [
                        "from" => 743,
                        "to" => 1704,
                    ],
                    [
                        "from" => 6484,
                        "to" => 4552,
                    ],
                    [
                        "from" => 4552,
                        "to" => 9631,
                    ],
                    [
                        "from" => 2562,
                        "to" => 6483,
                    ],
                    [
                        "from" => 6825,
                        "to" => 9284,
                    ],
                    [
                        "from" => 9255,
                        "to" => 5232,
                    ],
                    [
                        "from" => 6807,
                        "to" => 3629,
                    ],
                    [
                        "from" => 8759,
                        "to" => 5875,
                    ],
                    [
                        "from" => 1416,
                        "to" => 4211,
                    ],
                    [
                        "from" => 3503,
                        "to" => 325,
                    ],
                    [
                        "from" => 955,
                        "to" => 462,
                    ],
                    [
                        "from" => 4880,
                        "to" => 5583,
                    ],
                    [
                        "from" => 2979,
                        "to" => 6382,
                    ],
                    [
                        "from" => 743,
                        "to" => 5103,
                    ]
                ],
                'Categories' => ["Макароны", "Чай", "Вода", "Видео"]
            ],
            '3' => [
                'Racks' => [
                    [
                        "position"=> ["x"=> 78, "y"=> 318],
                        "width"=> 198,
                        "height"=> 18,
                        "label"=> "Макароны",
                        "fill"=> "blue",
                        "angle"=> 0,
                        "top"=> 7114,
                    ],
                    [
                        "position"=> ["x"=> 78, "y"=> 264],
                        "width"=> 198,
                        "height"=> 18,
                        "label"=> "Шоколад",
                        "fill"=> "blue",
                        "angle"=> 0,
                        "top"=> 3025,
                    ],
                    [
                        "position"=> ["x"=> 78, "y"=> 206],
                        "width"=> 198,
                        "height"=> 18,
                        "label"=> "Вода",
                        "fill"=> "blue",
                        "angle"=> 0,
                        "top"=> 7200,
                    ],
                    [
                        "position"=> ["x"=> 78, "y"=> 144],
                        "width"=> 198,
                        "height"=> 18,
                        "label"=> "Кетчуп",
                        "fill"=> "blue",
                        "angle"=> 0,
                        "top"=> 5378,
                    ],
                    [
                        "position"=> ["x"=> 324, "y"=> 144],
                        "width"=> 198,
                        "height"=> 18,
                        "label"=> "Видео",
                        "fill"=> "blue",
                        "angle"=> 0,
                        "top"=> 7602,
                    ],
                    [
                        "position"=> ["x"=> 324, "y"=> 204],
                        "width"=> 198,
                        "height"=> 18,
                        "label"=> "Консервы",
                        "fill"=> "blue",
                        "angle"=> 0,
                        "top"=> 5719,
                    ],
                    [
                        "position"=> ["x"=> 324, "y"=> 264],
                        "width"=> 198,
                        "height"=> 18,
                        "label"=> "Чай",
                        "fill"=> "blue",
                        "angle"=> 0,
                        "top"=> 6229,
                    ],
                    [
                        "position"=> ["x"=> 324, "y"=> 318],
                        "width"=> 198,
                        "height"=> 18,
                        "label"=> "Конфеты",
                        "fill"=> "blue",
                        "angle"=> 0,
                        "top"=> 404,
                    ],
                    [
                        "position"=> ["x"=> 288, "y"=> 348],
                        "width"=> 30,
                        "height"=> 30,
                        "label"=> "Старт",
                        "fill"=> "#E74C3C",
                        "angle"=> 0,
                        "top"=> 551,
                    ],
                    [
                        "position"=> ["x"=> 38, "y"=> 350],
                        "width"=> 15,
                        "height"=> 15,
                        "label"=> "",
                        "fill"=> "black",
                        "angle"=> 0,
                        "top"=> 2105,
                    ],
                    [
                        "position"=> ["x"=> 294, "y"=> 294],
                        "width"=> 15,
                        "height"=> 15,
                        "label"=> "",
                        "fill"=> "black",
                        "angle"=> 0,
                        "top"=> 1191,
                    ],
                    [
                        "position"=> ["x"=> 290, "y"=> 236],
                        "width"=> 15,
                        "height"=> 15,
                        "label"=> "",
                        "fill"=> "black",
                        "angle"=> 0,
                        "top"=> 2095,
                    ],
                    [
                        "position"=> ["x"=> 288, "y"=> 114],
                        "width"=> 15,
                        "height"=> 15,
                        "label"=> "",
                        "fill"=> "black",
                        "angle"=> 0,
                        "top"=> 8685,
                    ],
                    [
                        "position"=> ["x"=> 36, "y"=> 288],
                        "width"=> 15,
                        "height"=> 15,
                        "label"=> "",
                        "fill"=> "black",
                        "angle"=> 0,
                        "top"=> 6215,
                    ],
                    [
                        "position"=> ["x"=> 30, "y"=> 234],
                        "width"=> 15,
                        "height"=> 15,
                        "label"=> "",
                        "fill"=> "black",
                        "angle"=> 0,
                        "top"=> 1603,
                    ],
                    [
                        "position"=> ["x"=> 30, "y"=> 174],
                        "width"=> 15,
                        "height"=> 15,
                        "label"=> "",
                        "fill"=> "black",
                        "angle"=> 0,
                        "top"=> 6996,
                    ],
                    [
                        "position"=> ["x"=> 24, "y"=> 114],
                        "width"=> 15,
                        "height"=> 15,
                        "label"=> "",
                        "fill"=> "black",
                        "angle"=> 0,
                        "top"=> 6101,
                    ],
                    [
                        "position"=> ["x"=> 534, "y"=> 354],
                        "width"=> 15,
                        "height"=> 15,
                        "label"=> "",
                        "fill"=> "black",
                        "angle"=> 0,
                        "top"=> 2303,
                    ],
                    [
                        "position"=> ["x"=> 534, "y"=> 294],
                        "width"=> 15,
                        "height"=> 15,
                        "label"=> "",
                        "fill"=> "black",
                        "angle"=> 0,
                        "top"=> 7117,
                    ],
                    [
                        "position"=> ["x"=> 534, "y"=> 228],
                        "width"=> 15,
                        "height"=> 15,
                        "label"=> "",
                        "fill"=> "black",
                        "angle"=> 0,
                        "top"=> 2624,
                    ],
                    [
                        "position"=> ["x"=> 528, "y"=> 174],
                        "width"=> 15,
                        "height"=> 15,
                        "label"=> "",
                        "fill"=> "black",
                        "angle"=> 0,
                        "top"=> 7314,
                    ],
                    [
                        "position"=> ["x"=> 528, "y"=> 102],
                        "width"=> 15,
                        "height"=> 15,
                        "label"=> "",
                        "fill"=> "black",
                        "angle"=> 0,
                        "top"=> 8513,
                    ],
                    [
                        "position"=> ["x"=> 168, "y"=> 294],
                        "width"=> 15,
                        "height"=> 15,
                        "label"=> "",
                        "fill"=> "green",
                        "angle"=> 0,
                        "top"=> 9364,
                    ],
                    [
                        "position"=> ["x"=> 420, "y"=> 288],
                        "width"=> 15,
                        "height"=> 15,
                        "label"=> "",
                        "fill"=> "green",
                        "angle"=> 0,
                        "top"=> 3191,
                    ],
                    [
                        "position"=> ["x"=> 414, "y"=> 234],
                        "width"=> 15,
                        "height"=> 15,
                        "label"=> "",
                        "fill"=> "green",
                        "angle"=> 0,
                        "top"=> 486,
                    ],
                    [
                        "position"=> ["x"=> 414, "y"=> 180],
                        "width"=> 15,
                        "height"=> 15,
                        "label"=> "",
                        "fill"=> "green",
                        "angle"=> 0,
                        "top"=> 2619,
                    ],
                    [
                        "position"=> ["x"=> 408, "y"=> 102],
                        "width"=> 15,
                        "height"=> 15,
                        "label"=> "",
                        "fill"=> "green",
                        "angle"=> 0,
                        "top"=> 7506,
                    ],
                    [
                        "position"=> ["x"=> 162, "y"=> 240],
                        "width"=> 15,
                        "height"=> 15,
                        "label"=> "",
                        "fill"=> "green",
                        "angle"=> 0,
                        "top"=> 7503,
                    ],
                    [
                        "position"=> ["x"=> 156, "y"=> 174],
                        "width"=> 15,
                        "height"=> 15,
                        "label"=> "",
                        "fill"=> "green",
                        "angle"=> 0,
                        "top"=> 3099,
                    ],
                    [
                        "position"=> ["x"=> 156, "y"=> 102],
                        "width"=> 15,
                        "height"=> 15,
                        "label"=> "",
                        "fill"=> "green",
                        "angle"=> 0,
                        "top"=> 1590,
                    ],
                    [
                        "position"=> ["x"=> 288, "y"=> 180],
                        "width"=> 15,
                        "height"=> 15,
                        "label"=> "",
                        "fill"=> "black",
                        "angle"=> 0,
                        "top"=> 1050,
                    ],
                ],
                'Links' => [
                    [
                        "from"=> 551,
                        "to"=> 1191,
                    ],
                    [
                        "from"=> 551,
                        "to"=> 2303,
                    ],
                    [
                        "from"=> 551,
                        "to"=> 2105,
                    ],
                    [
                        "from"=> 2105,
                        "to"=> 6215,
                    ],
                    [
                        "from"=> 6215,
                        "to"=> 1603,
                    ],
                    [
                        "from"=> 1603,
                        "to"=> 6996,
                    ],
                    [
                        "from"=> 6996,
                        "to"=> 6101,
                    ],
                    [
                        "from"=> 6101,
                        "to"=> 1590,
                    ],
                    [
                        "from"=> 1590,
                        "to"=> 8685,
                    ],
                    [
                        "from"=> 8685,
                        "to"=> 7506,
                    ],
                    [
                        "from"=> 7506,
                        "to"=> 8513,
                    ],
                    [
                        "from"=> 8513,
                        "to"=> 7314,
                    ],
                    [
                        "from"=> 7314,
                        "to"=> 2624,
                    ],
                    [
                        "from"=> 2624,
                        "to"=> 7117,
                    ],
                    [
                        "from"=> 7117,
                        "to"=> 2303,
                    ],
                    [
                        "from"=> 1191,
                        "to"=> 2095,
                    ],
                    [
                        "from"=> 2619,
                        "to"=> 7314,
                    ],
                    [
                        "from"=> 2095,
                        "to"=> 486,
                    ],
                    [
                        "from"=> 486,
                        "to"=> 2624,
                    ],
                    [
                        "from"=> 1191,
                        "to"=> 3191,
                    ],
                    [
                        "from"=> 3191,
                        "to"=> 7117,
                    ],
                    [
                        "from"=> 1191,
                        "to"=> 9364,
                    ],
                    [
                        "from"=> 2095,
                        "to"=> 7503,
                    ],
                    [
                        "from"=> 2095,
                        "to"=> 1050,
                    ],
                    [
                        "from"=> 1050,
                        "to"=> 8685,
                    ],
                    [
                        "from"=> 1050,
                        "to"=> 3099,
                    ],
                    [
                        "from"=> 1050,
                        "to"=> 2619,
                    ],
                    [
                        "from"=> 3099,
                        "to"=> 6996,
                    ],
                    [
                        "from"=> 7503,
                        "to"=> 1603,
                    ],
                    [
                        "from"=> 9364,
                        "to"=> 6215,
                    ],
                    [
                        "from"=> 9364,
                        "to"=> 7114,
                    ],
                    [
                        "from"=> 7503,
                        "to"=> 3025,
                    ],
                    [
                        "from"=> 3099,
                        "to"=> 7200,
                    ],
                    [
                        "from"=> 1590,
                        "to"=> 5378,
                    ],
                    [
                        "from"=> 7506,
                        "to"=> 7602,
                    ],
                    [
                        "from"=> 2619,
                        "to"=> 5719,
                    ],
                    [
                        "from"=> 486,
                        "to"=> 6229,
                    ],
                    [
                        "from"=> 3191,
                        "to"=> 404,
                    ],
                ],
                'Categories' => ["Вода", "Видео", "Чай", "Макароны"]
//                'Categories' => ["Макароны", "Чай", "Вода", "Видео"]
            ]
        ];

        if (\Yii::$app->request->isPost) {

//            var_dump($data[$id]['Categories']);

            $finder = new FindPath($data[$id]['Categories'], $data[$id]['Links'], $data[$id]['Racks']);

            return $finder->findPath();

        }
    }
}
