<?php

namespace app\controllers;

use yii\rest\Controller;

class RacksController extends Controller
{
    public $racks = [
        '1' => [
            'Racks'=>[
                [   "position"=>["x"=>42,"y"=>44],
                    "width"=>198,
                    "height"=>18,
                    "label"=>"Макароны",
                    "fill"=>"blue",
                    "angle"=>0
                ],
                ["position"=>["x"=>42,"y"=>78],
                    "width"=>198,
                    "height"=>18,
                    "label"=>"шоколад",
                    "fill"=>"blue",
                    "angle"=>0],
                ["position"=>["x"=>42,"y"=>114],
                    "width"=>198,
                    "height"=>18,
                    "label"=>"Консервы",
                    "fill"=>"blue",
                    "angle"=>0],
                ["position"=>["x"=>42,"y"=>150],
                    "width"=>198,
                    "height"=>18,
                    "label"=>"Крупа",
                    "fill"=>"blue",
                    "angle"=>0],
                ["position"=>["x"=>42,"y"=>186],
                    "width"=>198,
                    "height"=>18,
                    "label"=>"Яйцо",
                    "fill"=>"blue",
                    "angle"=>0],
                ["position"=>["x"=>42,"y"=>222],
                    "width"=>198,
                    "height"=>18,
                    "label"=>"Вода",
                    "fill"=>"blue",
                    "angle"=>0],
                ["position"=>["x"=>42,"y"=>258],
                    "width"=>198,
                    "height"=>18,
                    "label"=>"Бельё",
                    "fill"=>"blue",
                    "angle"=>0],
                ["position"=>["x"=>42,"y"=>294],
                    "width"=>198,
                    "height"=>18,
                    "label"=>"Мыло",
                    "fill"=>"blue",
                    "angle"=>0],
                ["position"=>["x"=>42,"y"=>330],
                    "width"=>198,
                    "height"=>18,
                    "label"=>"Кетчуп",
                    "fill"=>"blue",
                    "angle"=>0],
                ["position"=>["x"=>264,"y"=>42],
                    "width"=>198,
                    "height"=>18,
                    "label"=>"Сад",
                    "fill"=>"blue",
                    "angle"=>0],
                ["position"=>["x"=>264,"y"=>78],
                    "width"=>198,
                    "height"=>18,
                    "label"=>"Фасад",
                    "fill"=>"blue",
                    "angle"=>0],
                ["position"=>["x"=>264,"y"=>114],
                    "width"=>198,
                    "height"=>18,
                    "label"=>"Вата",
                    "fill"=>"blue",
                    "angle"=>0],
                ["position"=>["x"=>264,"y"=>150],
                    "width"=>198,
                    "height"=>18,
                    "label"=>"Шашлык",
                    "fill"=>"blue",
                    "angle"=>0],
                ["position"=>["x"=>264,"y"=>186],
                    "width"=>198,
                    "height"=>18,
                    "label"=>"Балык",
                    "fill"=>"blue",
                    "angle"=>0],
                ["position"=>["x"=>264,"y"=>222],
                    "width"=>198,
                    "height"=>18,
                    "label"=>"Затык",
                    "fill"=>"blue",
                    "angle"=>0],
                ["position"=>["x"=>264,"y"=>258],
                    "width"=>198,
                    "height"=>18,
                    "label"=>"Втык",
                    "fill"=>"blue",
                    "angle"=>0],
                ["position"=>["x"=>264,"y"=>294],
                    "width"=>198,
                    "height"=>18,
                    "label"=>"Утык",
                    "fill"=>"blue",
                    "angle"=>0],
                ["position"=>["x"=>264,"y"=>330],
                    "width"=>198,
                    "height"=>18,
                    "label"=>"Перетык",
                    "fill"=>"blue",
                    "angle"=>0],
                ["position"=>["x"=>234,"y"=>360],
                    "width"=>30,
                    "height"=>30,
                    "label"=>"Старт",
                    "fill"=>"#E74C3C",
                    "angle"=>0]
            ]
        ],
        '2' => [
            'Racks' => [
                [
                    'position' => ["x" => 48, "y" => 16],
                    'width' => 198,
                    'height' => 18,
                    'label' => 'Кофе',
                    'fill' => 'blue',
                    'angle' => 0,
                    'top' => 3629,
                ],
                [
                    'position' => ["x" => 48, "y" => 19],
                    'width' => 198,
                    'height' => 18,
                    'label' => 'Кетчуп',
                    'fill' => 'blue',
                    'angle' => 0,
                    'top' => 5232,
                ],
                [
                    'position' => ["x" => 48, "y" => 23],
                    'width' => 198,
                    'height' => 18,
                    'label' => 'Консервы',
                    'fill' => 'blue',
                    'angle' => 0,
                    'top' => 9284,
                ],
                [
                    'position' => ["x" => 48, "y" => 12],
                    'width' => 198,
                    'height' => 18,
                    'label' => 'Чай',
                    'fill' => 'blue',
                    'angle' => 0,
                    'top' => 5875,
                ],
                [
                    'position' => ["x" => 48, "y" => 9],
                    'width' => 198,
                    'height' => 18,
                    'label' => 'Вино',
                    'fill' => 'blue',
                    'angle' => 0,
                    'top' => 4211,
                ],
                [
                    'position' => ["x" => 222, "y" => 18],
                    'width' => 198,
                    'height' => 18,
                    'label' => 'Вода',
                    'fill' => 'blue',
                    'angle' => 270,
                    'top' => 9631,
                ],
                [
                    'position' => ["x" => 48, "y" => 27],
                    'width' => 198,
                    'height' => 18,
                    'label' => 'Макароны',
                    'fill' => 'blue',
                    'angle' => 0,
                    'top' => 6483,
                ],
                [
                    'position' => ["x" => 264, "y" => 18],
                    'width' => 198,
                    'height' => 18,
                    'label' => 'Косметика',
                    'fill' => 'blue',
                    'angle' => 270,
                    'top' => 325,
                ],
                [
                    'position' => ["x" => 306, "y" => 18],
                    'width' => 198,
                    'height' => 18,
                    'label' => 'Хозтовары',
                    'fill' => 'blue',
                    'angle' => 270,
                    'top' => 462,
                ],
                [
                    'position' => ["x" => 348, "y" => 18],
                    'width' => 198,
                    'height' => 18,
                    'label' => 'Одежда',
                    'fill' => 'blue',
                    'angle' => 270,
                    'top' => 5583,
                ],
                [
                    'position' => ["x" => 390, "y" => 18],
                    'width' => 198,
                    'height' => 18,
                    'label' => 'Сад',
                    'fill' => 'blue',
                    'angle' => 270,
                    'top' => 6382,
                ],
                [
                    'position' => ["x" => 432, "y" => 18],
                    'width' => 198,
                    'height' => 18,
                    'label' => 'Видео',
                    'fill' => 'blue',
                    'angle' => 270,
                    'top' => 5103,
                ],
                [
                    'position' => ["x" => 270, "y" => 36],
                    'width' => 30,
                    'height' => 30,
                    'label' => 'Старт',
                    'fill' => '#E74C3C',
                    'angle' => 0,
                    'top' => 2698,
                ],
                [
                    'position' => ["x" => 270, "y" => 25],
                    'width' => 15,
                    'height' => 15,
                    'label' => '',
                    'fill' => 'black',
                    'angle' => 0,
                    'top' => 9331,
                ],
                [
                    'position' => ["x" => 270, "y" => 21],
                    'width' => 15,
                    'height' => 15,
                    'label' => '',
                    'fill' => 'black',
                    'angle' => 0,
                    'top' => 6484,
                ],
                [
                    'position' => ["x" => 262, "y" => 16],
                    'width' => 15,
                    'height' => 15,
                    'label' => '',
                    'fill' => 'black',
                    'angle' => 0,
                    'top' => 12,
                ],
                [
                    'position' => ["x" => 270, "y" => 14],
                    'width' => 15,
                    'height' => 15,
                    'label' => '',
                    'fill' => 'black',
                    'angle' => 0,
                    'top' => 2095,
                ],
                [
                    'position' => ["x" => 270, "y" => 10],
                    'width' => 15,
                    'height' => 15,
                    'label' => '',
                    'fill' => 'black',
                    'angle' => 0,
                    'top' => 8135,
                ],
                [
                    'position' => ["x" => 270, "y" => 6],
                    'width' => 15,
                    'height' => 15,
                    'label' => '',
                    'fill' => 'black',
                    'angle' => 0,
                    'top' => 9842,
                ],
                [
                    'position' => ["x" => 330, "y" => 6],
                    'width' => 15,
                    'height' => 15,
                    'label' => '',
                    'fill' => 'black',
                    'angle' => 0,
                    'top' => 9277,
                ],
                [
                    'position' => ["x" => 378, "y" => 6],
                    'width' => 15,
                    'height' => 15,
                    'label' => '',
                    'fill' => 'black',
                    'angle' => 0,
                    'top' => 7092,
                ],
                [
                    'position' => ["x" => 420, "y" => 6],
                    'width' => 15,
                    'height' => 15,
                    'label' => '',
                    'fill' => 'black',
                    'angle' => 0,
                    'top' => 9390,
                ],
                [
                    'position' => ["x" => 462, "y" => 6],
                    'width' => 15,
                    'height' => 15,
                    'label' => '',
                    'fill' => 'black',
                    'angle' => 0,
                    'top' => 9417,
                ],
                [
                    'position' => ["x" => 504, "y" => 6],
                    'width' => 15,
                    'height' => 15,
                    'label' => '',
                    'fill' => 'black',
                    'angle' => 0,
                    'top' => 1704,
                ],
                [
                    'position' => ["x" => 552, "y" => 6],
                    'width' => 15,
                    'height' => 15,
                    'label' => '',
                    'fill' => 'black',
                    'angle' => 0,
                    'top' => 7327,
                ],
                [
                    'position' => ["x" => 270, "y" => 30],
                    'width' => 15,
                    'height' => 15,
                    'label' => '',
                    'fill' => 'black',
                    'angle' => 0,
                    'top' => 9834,
                ],
                [
                    'position' => ["x" => 330, "y" => 30],
                    'width' => 15,
                    'height' => 15,
                    'label' => '',
                    'fill' => 'black',
                    'angle' => 0,
                    'top' => 7394,
                ],
                [
                    'position' => ["x" => 378, "y" => 30],
                    'width' => 15,
                    'height' => 15,
                    'label' => '',
                    'fill' => 'black',
                    'angle' => 0,
                    'top' => 1829,
                ],
                [
                    'position' => ["x" => 420, "y" => 30],
                    'width' => 15,
                    'height' => 15,
                    'label' => '',
                    'fill' => 'black',
                    'angle' => 0,
                    'top' => 2456,
                ],
                [
                    'position' => ["x" => 458, "y" => 30],
                    'width' => 15,
                    'height' => 15,
                    'label' => '',
                    'fill' => 'black',
                    'angle' => 0,
                    'top' => 4010,
                ],
                [
                    'position' => ["x" => 504, "y" => 30],
                    'width' => 15,
                    'height' => 15,
                    'label' => '',
                    'fill' => 'black',
                    'angle' => 0,
                    'top' => 3362,
                ],
                [
                    'position' => ["x" => 552, "y" => 30],
                    'width' => 15,
                    'height' => 15,
                    'label' => '',
                    'fill' => 'black',
                    'angle' => 0,
                    'top' => 8053,
                ],
                [
                    'position' => ["x" => 18, "y" => 30],
                    'width' => 15,
                    'height' => 15,
                    'label' => '',
                    'fill' => 'black',
                    'angle' => 0,
                    'top' => 9999,
                ],
                [
                    'position' => ["x" => 16, "y" => 25],
                    'width' => 15,
                    'height' => 15,
                    'label' => '',
                    'fill' => 'black',
                    'angle' => 0,
                    'top' => 6496,
                ],
                [
                    'position' => ["x" => 12, "y" => 22],
                    'width' => 15,
                    'height' => 15,
                    'label' => '',
                    'fill' => 'black',
                    'angle' => 0,
                    'top' => 9475,
                ],
                [
                    'position' => ["x" => 12, "y" => 18],
                    'width' => 15,
                    'height' => 15,
                    'label' => '',
                    'fill' => 'black',
                    'angle' => 0,
                    'top' => 154,
                ],
                [
                    'position' => ["x" => 12, "y" => 14],
                    'width' => 15,
                    'height' => 15,
                    'label' => '',
                    'fill' => 'black',
                    'angle' => 0,
                    'top' => 6982,
                ],
                [
                    'position' => ["x" => 12, "y" => 11],
                    'width' => 15,
                    'height' => 15,
                    'label' => '',
                    'fill' => 'black',
                    'angle' => 0,
                    'top' => 3959,
                ],
                [
                    'position' => ["x" => 12, "y" => 6],
                    'width' => 15,
                    'height' => 15,
                    'label' => '',
                    'fill' => 'black',
                    'angle' => 0,
                    'top' => 2515,
                ],
                [
                    'position' => ["x" => 132, "y" => 25],
                    'width' => 15,
                    'height' => 15,
                    'label' => '',
                    'fill' => 'green',
                    'angle' => 0,
                    'top' => 2562,
                ],
                [
                    'position' => ["x" => 132, "y" => 21],
                    'width' => 15,
                    'height' => 15,
                    'label' => '',
                    'fill' => 'green',
                    'angle' => 0,
                    'top' => 6825,
                ],
                [
                    'position' => ["x" => 132, "y" => 18],
                    'width' => 15,
                    'height' => 15,
                    'label' => '',
                    'fill' => 'green',
                    'angle' => 0,
                    'top' => 9255,
                ],
                [
                    'position' => ["x" => 132, "y" => 14],
                    'width' => 15,
                    'height' => 15,
                    'label' => '',
                    'fill' => 'green',
                    'angle' => 0,
                    'top' => 6807,
                ],
                [
                    'position' => ["x" => 132, "y" => 10],
                    'width' => 15,
                    'height' => 15,
                    'label' => '',
                    'fill' => 'green',
                    'angle' => 0,
                    'top' => 8759,
                ],
                [
                    'position' => ["x" => 132, "y" => 6],
                    'width' => 15,
                    'height' => 15,
                    'label' => '',
                    'fill' => 'green',
                    'angle' => 0,
                    'top' => 1416,
                ],
                [
                    'position' => ["x" => 334, "y" => 15],
                    'width' => 15,
                    'height' => 15,
                    'label' => '',
                    'fill' => 'green',
                    'angle' => 0,
                    'top' => 3503,
                ],
                [
                    'position' => ["x" => 378, "y" => 15],
                    'width' => 15,
                    'height' => 15,
                    'label' => '',
                    'fill' => 'green',
                    'angle' => 0,
                    'top' => 955,
                ],
                [
                    'position' => ["x" => 420, "y" => 15],
                    'width' => 15,
                    'height' => 15,
                    'label' => '',
                    'fill' => 'green',
                    'angle' => 0,
                    'top' => 4880,
                ],
                [
                    'position' => ["x" => 462, "y" => 16],
                    'width' => 15,
                    'height' => 15,
                    'label' => '',
                    'fill' => 'green',
                    'angle' => 0,
                    'top' => 2979,
                ],
                [
                    'position' => ["x" => 504, "y" => 16],
                    'width' => 15,
                    'height' => 15,
                    'label' => '',
                    'fill' => 'green',
                    'angle' => 0,
                    'top' => 743,
                ],
                [
                    'position' => ["x" => 294, "y" => 20],
                    'width' => 15,
                    'height' => 15,
                    'label' => '',
                    'fill' => 'green',
                    'angle' => 0,
                    'top' => 4552,
                ],
            ],
        ]
    ];

    public function init()
    {
        parent::init();
        \Yii::$app->user->enableSession = false;
        \Yii::$app->user->enableAutoLogin = false;
    }

    public function actionIndex(string $id)
    {
        if (\Yii::$app->request->isPost) {

//            return $this->racks[$id];,
//            return '{Status: OK}';,
            return \Yii::$app->request->post();
        }

        return $this->racks[$id];
    }
}
